app/models/packs.py
from ..extensions import db
from .channels import Channels


class Packs(db.Model):
    __tablename__ = 'packs'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    channels = db.relationship(Channels, backref='packs', lazy='dynamic')
    pack_name = db.Column(db.String(255), nullable=False)
    description = db.Column(db.String(255), nullable=True)

app/routes/packs.py
from flask import Blueprint, render_template, request, redirect, flash
from flask_login import login_required

from ..extensions import db
from ..forms import CreatePackForm
from ..models.packs import Packs

pack = Blueprint('pack', __name__)


@pack.route('/pack/list', methods=['GET'])
@login_required
def all():
    return render_template('pack/all.html',
                           packs=Packs.query.order_by(Packs.pack_name).all())


@pack.route('/pack/create', methods=['GET', 'POST'])
@login_required
def create():
    form = CreatePackForm()
    if form.validate_on_submit():
        new_pack = Packs(pack_name=form.name.data,
                         description=form.description.data)
        try:
            db.session.add(new_pack)
            db.session.commit()
            flash(f"Pack created", "success")
        except Exception as e:
            print(str(e))
            flash(f"Pack creation failed", "danger")

    return render_template('pack/create.html', form=form)


@pack.route('/pack/<int:id>/update', methods=['GET', 'POST'])
@login_required
def update(id):
    pack = Packs.query.get(id)
    if request.method == 'POST':
        pack.pack_name = request.form.get('pack_name')
        pack.description = request.form.get('description')
        try:
            db.session.commit()
            return redirect('pack/list')
        except Exception as e:
            print(str(e))
            flash(f"Pack update failed", "danger")
    else:
        return render_template('pack/update.html', pack=pack)


@pack.route('/pack/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete(id):
    pack = Packs.query.get(id)
    try:
        db.session.delete(pack)
        db.session.commit()
        return redirect('/')
    except Exception as e:
        print(str(e))
        flash(f"Pack deletion failed", "danger")
        db.session.rollback()

app/templates/pack/all.html
{% extends 'main/base.html' %}

{% block title %}All Packs{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/table.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/font-awesome.min.css') }}">
{% endblock %}

{% block content %}
<div class="table-responsive custom-table-responsive">
  <table class="table custom-table">
    <thead>
        <th scope="col">Pack Name</th>
        <th scope="col">Pack Description</th>
        <th scope="col">Update</th>
    </thead>
    <tbody>
      {% for pack in packs %}
      <tr scope="row">
        <td>{{ pack.pack_name }}</td>
        <td>{{ pack.description }}</td>
      {% if current_user.is_authenticated %}
        <td>
          <a href="{{ url_for('pack.update', id=pack.id) }}" class="btn btn-sm btn-secondary"><span class="fa fa-edit"></span></a>
          <a href="{{ url_for('pack.delete', id=pack.id) }}" class="btn btn-sm btn-danger"><span class="fa fa-trash"></span></a>
        </td>
      {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/pack/create.html
{% extends 'main/base.html' %}

{% block title %}Add Pack{% endblock %}

{% block content %}

<form method="post" enctype="multipart/form-data" class="form-control d-flex flex-column gap-2">
    {{ form.csrf_token }}
    {{ form.name(class="form-control", placeholder="Pack Name") }}
    {{ form.description(class="form-control", placeholder="Description") }}
    {{ form.submit(class="btn btn-success") }}
</form>

{% endblock %}