app/routes/channels.py
from flask import Blueprint, render_template, request, redirect, flash
from flask_login import login_required

from ..extensions import db
from ..functions import save_picture
from ..forms import CreateChannelForm
from ..models.channels import Channels
from ..models.packs import Packs

channel = Blueprint('channel', __name__)


@channel.route('/channel/list', methods=['GET'])
@login_required
def all():
    channels = Channels.query.order_by(Channels.number).all()
    return render_template('channel/all.html', channels=channels)


@channel.route('/channel/create', methods=['GET', 'POST'])
@login_required
def create():
    form = CreateChannelForm()
    form.pack.choices = [p.pack_name for p in Packs.query]
    if form.validate_on_submit():
        channel_filename = save_picture(form.logo.data)
        pack_id = Packs.query.filter_by(pack_name=form.pack.data).first().id
        new_channel = Channels(number=form.number.data,
                               channel_name=form.name.data,
                               logo=channel_filename,
                               description=form.description.data,
                               pack=pack_id)
        try:
            db.session.add(new_channel)
            db.session.commit()
            flash(f"Channel created", "success")
            return redirect('/channel/list')
        except Exception as e:
            print(str(e))
            flash(f"Failed to create channel", "danger")

    return render_template('channel/create.html', form=form)


@channel.route('/channel/<int:id>/update', methods=['GET', 'POST'])
@login_required
def update(id):
    channel = Channels.query.get(id)
    # form = CreateChannelForm()
    # form.pack.data = Channels.query.filter_by(id=channel.pack).first().id
    # form.pack.choices = [p.pack_name for p in Packs.query]
    if request.method == 'POST':
        # for value in channel:
        #     channel.value = request.form.get(value)
        channel.channel_name = request.form.get('channel_name')
        channel.description = request.form.get('description')
        #channel.pack = Packs.query.filter_by(id=channel.pack).first().name
        try:
            db.session.commit()
            return redirect('/channel/list')
        except Exception as e:
            print('Updating Channel Failed', str(e))
            db.session.rollback()
    else:
        return render_template('channel/update.html', channel=channel)


@channel.route('/channel/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete(id):
    channel = Channels.query.get(id)
    try:
        db.session.delete(channel)
        db.session.commit()
        return redirect('/')
    except Exception as e:
        print('Deleting Channel Failed', str(e))
        db.session.rollback()

app/routes/main.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('main/index.html')

app/routes/packs.py
from flask import Blueprint, render_template, request, redirect, flash
from flask_login import login_required

from ..extensions import db
from ..forms import CreatePackForm
from ..models.packs import Packs

pack = Blueprint('pack', __name__)


@pack.route('/pack/list', methods=['GET'])
@login_required
def all():
    return render_template('pack/all.html',
                           packs=Packs.query.order_by(Packs.pack_name).all())


@pack.route('/pack/create', methods=['GET', 'POST'])
@login_required
def create():
    form = CreatePackForm()
    if form.validate_on_submit():
        new_pack = Packs(pack_name=form.name.data,
                         description=form.description.data)
        try:
            db.session.add(new_pack)
            db.session.commit()
            flash(f"Pack created", "success")
        except Exception as e:
            print(str(e))
            flash(f"Pack creation failed", "danger")

    return render_template('pack/create.html', form=form)


@pack.route('/pack/<int:id>/update', methods=['GET', 'POST'])
@login_required
def update(id):
    pack = Packs.query.get(id)
    if request.method == 'POST':
        pack.pack_name = request.form.get('pack_name')
        pack.description = request.form.get('description')
        try:
            db.session.commit()
            return redirect('pack/list')
        except Exception as e:
            print(str(e))
            flash(f"Pack update failed", "danger")
    else:
        return render_template('pack/update.html', pack=pack)


@pack.route('/pack/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete(id):
    pack = Packs.query.get(id)
    try:
        db.session.delete(pack)
        db.session.commit()
        return redirect('/')
    except Exception as e:
        print(str(e))
        flash(f"Pack deletion failed", "danger")
        db.session.rollback()

app/routes/user.py
from flask import Blueprint, render_template, request, redirect, flash, url_for
from flask_login import login_user, login_required, logout_user
from werkzeug.security import check_password_hash, generate_password_hash

from ..functions import save_picture
from ..extensions import db
from ..forms import RegistrationForm, LoginForm
from ..models.user import User


user = Blueprint('user', __name__)


@user.route('/user/list', methods=['GET'])
@login_required
def user_list():
    return render_template('/user/all.html', users=User.query.all())


@user.route('/user/create', methods=['GET', 'POST'])
@login_required
def create():
    username = request.form.get('user_name')
    firstname = request.form.get('firstname')
    lastname = request.form.get('lastname')
    password = request.form.get('password')
    email = request.form.get('email')
    subscription = request.form.get('subscription')

    if request.method == 'POST':
        try:
            hash_pwd = generate_password_hash(password)
            user = User(username=username,
                        firstname=firstname,
                        lastname=lastname,
                        password=hash_pwd,
                        email=email,
                        plan=subscription)
            db.session.add(user)
            db.session.commit()
            return redirect('/user/list')
        except Exception as e:
            print('Adding User Failed', str(e))
            db.session.rollback()

    return render_template('user/create.html')


@user.route('/user/<int:id>/update', methods=['GET', 'POST'])
@login_required
def update(id):
    user = User.query.get(id)
    if request.method == 'POST':
        user.username = request.form.get('username')
        user.firstname = request.form.get('firstname')
        user.lastname = request.form.get('lastname')
        user.email = request.form.get('email')

        try:
            db.session.commit()
            return redirect('/user/list')
        except Exception as e:
            print('Updating User Failed', str(e))
            db.session.rollback()
    else:
        return render_template('user/update.html', user=user)


@user.route('/user/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete(id):
    user = User.query.get(id)
    try:
        db.session.delete(user)
        db.session.commit()
        return redirect('/user/list')
    except Exception as e:
        print('Deleting User Failed', str(e))
        db.session.rollback()


# @user.route('/user/login', methods=['GET', 'POST'])
# def login_page():
#     login = request.form.get('login')
#     password = request.form.get('password')
#     if login and password:
#         user = User.query.filter_by(username=login).first()
#         if user and check_password_hash(user.password, password):
#             login_user(user)
#             next_page = request.args.get('next')
#             # flash(f"You have been logged in as {user.username}", "success")
#             return redirect(next_page) if next_page else redirect(url_for('main.index'))
#         else:
#             flash(f"Login or password incorrect", "danger")
#     # else:
#     #     flash("Please check your login and password")
#
#     return render_template('user/login.html')
#     #return render_template('main/index.html')

@user.route('/user/login', methods=['GET', 'POST'])
def login_page():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        if username and password:
            user = User.query.filter_by(username=username).first()
            if user and check_password_hash(user.password, password):
                login_user(user)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.index'))
            else:
                flash('Login Unsuccessful. Please check username and password', 'danger')

    return render_template('user/login.html', form=form)


# @user.route('/user/register', methods=['GET', 'POST'])
# def register():
#     login = request.form.get('login')
#     password = request.form.get('password')
#     password2 = request.form.get('password2')
#     email = request.form.get('email')
#
#     if request.method == 'POST':
#         if not (login or password or password2):
#             flash(f"Please, fill all fields.", "danger")
#         elif password != password2:
#             flash(f"Passwords do not match", "danger")
#         else:
#             hash_pwd = generate_password_hash(password)
#             new_user = User(username=login, password=hash_pwd, email=email)
#             try:
#                 db.session.add(new_user)
#                 db.session.commit()
#                 flash(f"You have successfully registered.", "success")
#                 return redirect(url_for('user.login_page'))
#             except Exception as e:
#                 print(str(e))
#                 flash(f"Error occurred", "danger")
#     return render_template('user/register.html')


@user.route('/user/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hash_pwd = generate_password_hash(form.password.data)
        avatar_filename = save_picture(form.avatar.data)
        new_user = User(username=form.username.data,
                        password=hash_pwd,
                        email=form.email.data,
                        avatar=avatar_filename)
        try:
            db.session.add(new_user)
            db.session.commit()
            flash(f"You have successfully registered.", "success")
            return redirect(url_for('user.login_page'))
        except Exception as e:
            print(str(e))
            flash(f"Registration Failed", "danger")
    # else:
    #     #print('Registration Failed')

    return render_template('user/register.html', form=form)


@user.route('/user/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login_page'))


@user.after_request
def redirect_to_login(response):
    if response.status_code == 401:
        return redirect(url_for('user.login_page') + '?next=' + request.url)

    return response

app/templates/main/_flash.html
<!-- Flash message -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
<!-- Flash message -->

app/templates/main/_footer.html
<ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="#" class="nav-link px-2">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">Pricing</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">About</a></li>
</ul>
<p class="text-center">© 2025 Smotrish, Inc</p>

app/templates/main/_header.html
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
    <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <img class="header__img" src="{{ url_for('static', filename='img/logo2.png') }}" alt="smotrish">
    </a>

    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{{ url_for('main.index') }}" class="nav-link px-2 text-secondary">Home</a></li>
            {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('channel.create') }}" class="nav-link px-2 text-black">Add Channel</a></li>
        <li><a href="{{ url_for('channel.all') }}" class="nav-link px-2 text-black">Channels List</a></li>
        <li><a href="{{ url_for('pack.create') }}" class="nav-link px-2 text-black">Add Pack</a></li>
        <li><a href="{{ url_for('pack.all') }}" class="nav-link px-2 text-black">Packs List</a></li>
        <li><a href="{{ url_for('user.create') }}" class="nav-link px-2 text-black">Add User</a></li>
        <li><a href="{{ url_for('user.user_list') }}" class="nav-link px-2 text-black">Users List</a></li>
            {% endif %}

    </ul>

    <div class="text-end">
        {% if current_user.is_authenticated %}
            <span>Welcome, {{ current_user.username }}</span>
            <a href="{{ url_for('user.logout') }}" type="button" class="btn btn-outline-info me-2">Logout</a>
        {% else %}
        <a href="{{ url_for('user.login_page') }}" type="button" class="btn btn-outline-dark me-2">Login</a>
        <a href="{{ url_for('user.register') }}" class="btn btn-outline-warning">Register</a>
        {% endif %}
    </div>
</div>

app/templates/main/_sidebar.html
<div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link active" aria-current="page">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          Home
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
          Dashboard
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
          Orders
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
          Products
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
          Customers
        </a>
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>mdo</strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul>
    </div>
  </div>

app/templates/main/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">
    {% block style %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
<div class="page">
    <header class="header">
        {% include 'main/_header.html' %}
    </header>
    <main class="content">
        {% include 'main/_flash.html' %}
        <h1>{{ self.title() }}</h1>
        {% block content %}{% endblock %}
    </main>
    <footer>
        <footer class="py3 my-4">
            {% include 'main/_footer.html' %}
        </footer>
    </footer>
</div>

    <script src="{{ url_for('static', filename='js/libs/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
{% block script %}{% endblock %}
</body>
</html>

app/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}
IPTV Channels Web board management
{% endblock %}

{% block content %}<h1>Start with adding some channels</h1>{% endblock %}