app/models/channels.py
from ..extensions import db


class Channels(db.Model):
    __tablename__ = 'channels'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    number = db.Column(db.Integer, nullable=False)
    channel_name = db.Column(db.String(128), nullable=False)
    logo = db.Column(db.String(255), nullable=True)
    description = db.Column(db.String(256), nullable=True)
    pack = db.Column(db.Integer, db.ForeignKey('packs.id', ondelete='CASCADE'))

app/routes/channels.py
from flask import Blueprint, render_template, request, redirect, flash
from flask_login import login_required

from ..extensions import db
from ..functions import save_picture
from ..forms import CreateChannelForm
from ..models.channels import Channels
from ..models.packs import Packs

channel = Blueprint('channel', __name__)


@channel.route('/channel/list', methods=['GET'])
@login_required
def all():
    channels = Channels.query.order_by(Channels.number).all()
    return render_template('channel/all.html', channels=channels)


@channel.route('/channel/create', methods=['GET', 'POST'])
@login_required
def create():
    form = CreateChannelForm()
    form.pack.choices = [p.pack_name for p in Packs.query]
    if form.validate_on_submit():
        channel_filename = save_picture(form.logo.data)
        pack_id = Packs.query.filter_by(pack_name=form.pack.data).first().id
        new_channel = Channels(number=form.number.data,
                               channel_name=form.name.data,
                               logo=channel_filename,
                               description=form.description.data,
                               pack=pack_id)
        try:
            db.session.add(new_channel)
            db.session.commit()
            flash(f"Channel created", "success")
            return redirect('/channel/list')
        except Exception as e:
            print(str(e))
            flash(f"Failed to create channel", "danger")

    return render_template('channel/create.html', form=form)


@channel.route('/channel/<int:id>/update', methods=['GET', 'POST'])
@login_required
def update(id):
    channel = Channels.query.get(id)
    # form = CreateChannelForm()
    # form.pack.data = Channels.query.filter_by(id=channel.pack).first().id
    # form.pack.choices = [p.pack_name for p in Packs.query]
    if request.method == 'POST':
        # for value in channel:
        #     channel.value = request.form.get(value)
        channel.channel_name = request.form.get('channel_name')
        channel.description = request.form.get('description')
        #channel.pack = Packs.query.filter_by(id=channel.pack).first().name
        try:
            db.session.commit()
            return redirect('/channel/list')
        except Exception as e:
            print('Updating Channel Failed', str(e))
            db.session.rollback()
    else:
        return render_template('channel/update.html', channel=channel)


@channel.route('/channel/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete(id):
    channel = Channels.query.get(id)
    try:
        db.session.delete(channel)
        db.session.commit()
        return redirect('/')
    except Exception as e:
        print('Deleting Channel Failed', str(e))
        db.session.rollback()

app/templates/channel/all.html
{% extends 'main/base.html' %}

{% block title %}All Channels{% endblock %}

{% block style %}
    {% assets 'channel_all_css' %}
        <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
{% endblock %}


{% block content %}
<div class="table-responsive custom-table-responsive">
  <table class="table custom-table">
    <thead>
        <th scope="col">Channel Number</th>
        <th scope="col">Channel Name</th>
        <th scope="col">Channel Description</th>
        <th scope="col">Logo</th>
        <th scope="col">Packet Name</th>
        <th scope="col">Update</th>
    </thead>
    <tbody>
      {% for channel in channels %}
      <tr scope="row">
        <td>{{ channel.number }}</td>
        <td>{{ channel.channel_name }}</td>
        <td>{{ channel.description }}</td>
        <td><img width="30px" height="30px" src="{{ url_for('static', filename='uploads/' + channel.logo) }}" alt="Logo"></td>
        <td>{{ channel.packs.pack_name }}</td>
      {% if current_user.is_authenticated %}
        <td>
          <a href="{{ url_for('channel.update', id=channel.id) }}" class="btn btn-sm btn-secondary"><span class="fa fa-edit"></span></a>
          <a href="{{ url_for('channel.delete', id=channel.id) }}" class="btn btn-sm btn-danger"><span class="fa fa-trash"></span></a>
        </td>
      {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

{% block script %}
	{% assets 'channel_all_js' %}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock %}

app/templates/channel/create.html
{% extends 'main/base.html' %}

{% block title %}Add Channel{% endblock %}

{% block content %}
<!--
<form method="post" class="form-control d-flex flex-column gap-2">
    <input type="text" class="form-control" placeholder="Channel name" name="channel_name">
    <input type="text" class="form-control" placeholder="Description(Optional)" name="description">
    <button class="btn btn-success" type="submit">Add channel</button>
</form>
-->

<form method="post" enctype="multipart/form-data" class="form-control d-flex flex-column gap-2">
    {{ form.csrf_token }}
    {{ form.number(class="form-control", placeholder="Channel Number") }}
    {{ form.name(class="form-control", placeholder="Channel Name") }}
    {{ form.description(class="form-control", placeholder="Description") }}
    {{ form.logo(class="form-control") }}
    {{ form.pack(class="form-control", placeholder="Packet Name") }}
    {{ form.submit(class="btn btn-success") }}
</form>

{% endblock %}

app/templates/channel/update.html
{% extends 'main/base.html' %}

{% block title %}Update Channel = <b>"{{channel.channel_name}}"</b>{% endblock %}

{% block content %}

<form method="post" class="form-control d-flex flex-column gap-2">
    <input value="{{ channel.number }}" type="text" class="form-control" placeholder="channel number" name="number">
    <input value="{{ channel.channel_name }}" type="text" class="form-control" placeholder="channel name" name="channel_name">
    <input value="{{ channel.description }}" type="text" class="form-control" placeholder="Description" name="description">
    <button class="btn btn-success" type="submit">Save channel</button>
</form>
<!--
<form method="post" enctype="multipart/form-data" class="form-control d-flex flex-column gap-2">
{#    {{ form.csrf_token }}#}
{#    {{ form.number(class="form-control", placeholder="Channel Number") }}#}
{#    {{ form.name(class="form-control", placeholder="Channel Name") }}#}
{#    {{ form.description(class="form-control", placeholder="Description") }}#}
{#    {{ form.logo(class="form-control") }}#}
{#    {{ form.pack(class="form-control", placeholder="Packet Name") }}#}
{#    {{ form.submit(class="btn btn-success") }}#}
</form>
-->
{% endblock %}